<div id="messages">
       <div class="message"> MessageContents 
           <button type="button" class="primary">ClickMe</button>
       </div>
</div>
<div id="popup-mpdal" style="display : none;">
    <h1> Hi I'm here.... </h1>
	<button id="test-ong-noi">Chan</button>
	<div id="content-add-dream"></div>

</div>
<script type="text/javascript">// <![CDATA[
require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ],
    function($, modal) {
       $('#messages').click(function(){
           /*  alert({
               content: $(event.target).parent().text()
            }) */
			 var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'popup mpdal title',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-mpdal'));
            $('#popup-mpdal').modal('openModal');
			console.log('test');
       });
	   $('#test-ong-noi').click(function()
	   {
		  // console.log('Ong Noi Noi Uong')
		  $('#content-add-dream').html('Mai van uoc');
	   })
    }
);
// ]]></script>
</div>