<!--div data-mage-init='{"module3": {"option_1": "Mai uoc Vui vai"}}'>
    <span class="mai-uoc-kaka">MAi uoc</span>
	<button data-role="test_action_element" type="button" title="<?php echo __('Search') ?>" class="action submit primary">
		<span><?php echo __('Clic here') ?></span>
	</button>
</div=-->
<div data-mage-init='{"module4": {}}'>
    <span class="mai-uoc-kaka">Initialize a JS component in a PHTML template</span>
</div>
<br/>
<div id="mai-uoc-keke">
    <span class="mai-uoc-kaka">Initialize a JS component in a PHTML template 2</span>
	<button id="test-new-click-2" type="button" title="<?php echo __('Bam Vo') ?>" class="action submit primary">
		<span><?php echo __('Click Here') ?></span>
	</button>
</div>
<script type="text/x-magento-init">
    {
        "#mai-uoc-keke": {
            "module5": {}
        }
    }
</script>
