<div class="simplenews">
   <?php
		echo get_class($block);
		$block->getDreamProduct();
      $newsCollection = $block->getCollection();
      if ($newsCollection->getSize() > 0) :
   ?>
      <div class="toolbar top">
         <?php //echo $block->getPagerHtml(); ?>
      </div>
 
      <ul>
         <?php foreach ($newsCollection as $news) : ?>
            <li>
               <div class="simplenews-list">
                  <a class="news-title" href="<?php echo $this->getUrl('dream/index/view',
 ['id' => $news->getId()]) ?>"><?php echo $news->getTitle() ?></a>
                  <div class="simplenews-list-content">
                     <?php echo $news->getSummary() ?>
                  </div>
               </div>
            </li>
         <?php endforeach; ?>
      </ul>
 
      <div style="clear: both"></div>
 
      <div class="toolbar-bottom">
         <div class="toolbar bottom">
            <?php echo $block->getPagerHtml(); ?>
         </div>
      </div>
   <?php else : ?>
      <p><?php echo __('Have no article!') ?></p>
   <?php endif; ?>
   <!-- test show block-->
   <?php $a = $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('MST_Dream::ajax.phtml')->toHtml(); 
		echo $a;
   ?>
   <input id="mai-uoc-kaka" type="text" name="test_uoc_mai" />
	<div id="mai-uoc-content-kaka"></div>
</div>
<script type="text/javascript">
    require(['jquery'],function($){
		$('#mai-uoc-kaka').click(function(){
			console.log("I was clicked");
			var urlBooking = 'http://127.0.0.1/mage21/dream/index/mai'
			$.ajax({
				url : urlBooking,
				dataType : 'json',
				type : 'POST',
				data : {},
				success : function(res)
				{
					$('#mai-uoc-content-kaka').html(res.maiuoc);
				},
				error : function()
				{
					console.log('error');
				}
			});
		})
    }); 
</script>